import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js";
import { getFirestore, collection, getDocs, query, orderBy, doc, updateDoc, setDoc, addDoc, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAaaABQB1T_SaZ6TARafIXjJ6Zk-upjLO0",authDomain:"prayer-projec.firebaseapp.com",projectId:"prayer-projec",storageBucket:"prayer-projec.firebasestorage.app",messagingSenderId:"47966669764",appId:"1:47966669764:web:b875d2ea5bf75e3b7b3291"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let apps=[],chapters=[],approvedChapters=[],volunteers=[],activities=[],serviceLogs=[],careProjects=[],training=[],assignments=[],contacts=[],leaves=[];
injectAdminStyles();injectAdminLogin();createProvisionModal();
onAuthStateChanged(auth,async user=>{if(!user){showLogin();return;}hideLogin();await loadAll();});
async function readCol(name,ordered=true){try{return await getDocs(ordered?query(collection(db,name),orderBy('createdAt','desc')):collection(db,name))}catch(e){return {forEach(){}}}}
async function loadAll(){try{const [a,c,ac,v,u,s,p,t,as,co,l]=await Promise.all([readCol('volunteer_applications'),readCol('volunteer_chapter_requests'),readCol('volunteer_chapters'),readCol('volunteers',false),readCol('volunteer_activity_updates'),readCol('volunteer_service_logs'),readCol('volunteer_care_projects'),readCol('volunteer_training_completions'),readCol('volunteer_assignments'),readCol('volunteer_contacts'),readCol('volunteer_leave_requests')]);apps=[];chapters=[];approvedChapters=[];volunteers=[];activities=[];serviceLogs=[];careProjects=[];training=[];assignments=[];contacts=[];leaves=[];a.forEach(d=>apps.push({id:d.id,...d.data()}));c.forEach(d=>chapters.push({id:d.id,...d.data()}));ac.forEach(d=>approvedChapters.push({id:d.id,...d.data()}));v.forEach(d=>volunteers.push({id:d.id,...d.data()}));u.forEach(d=>activities.push({id:d.id,...d.data()}));s.forEach(d=>serviceLogs.push({id:d.id,...d.data()}));p.forEach(d=>careProjects.push({id:d.id,...d.data()}));t.forEach(d=>training.push({id:d.id,...d.data()}));as.forEach(d=>assignments.push({id:d.id,...d.data()}));co.forEach(d=>contacts.push({id:d.id,...d.data()}));l.forEach(d=>leaves.push({id:d.id,...d.data()}));render();}catch(e){console.error(e);$('applicationList').innerHTML='Could not load volunteer records. Check Firestore rules.';}}
function render(){setText('appCount',apps.length);setText('chapterCount',chapters.length+approvedChapters.length);setText('volunteerCount',volunteers.length);$('applicationList').innerHTML=apps.length?apps.map(appCard).join(''):'<div>No applications yet.</div>';$('chapterList').innerHTML=[...chapters.map(chapterCard),...approvedChapters.map(activeChapterCard)].join('')||'<div>No chapters or chapter requests yet.</div>';if($('volunteerList'))$('volunteerList').innerHTML=volunteers.length?volunteers.map(volunteerCard).join(''):'<div>No volunteers activated yet.</div>';$('activityList').innerHTML=[...activities.map(activityCard),...serviceLogs.map(serviceLogCard),...careProjects.map(careProjectCard),...training.map(trainingCard),...assignments.map(assignmentCard),...contacts.map(contactCard),...leaves.map(leaveCard)].join('')||'<div>No volunteer updates yet.</div>';bindButtons();}
function bindButtons(){document.querySelectorAll('.accept-app').forEach(b=>b.onclick=()=>openProvisionModal(b.dataset.id));document.querySelectorAll('.reject-app').forEach(b=>b.onclick=()=>setDocStatus('volunteer_applications',b.dataset.id,'rejected','application_rejected'));document.querySelectorAll('.delete-app').forEach(b=>b.onclick=()=>deleteApplication(b.dataset.id));document.querySelectorAll('.approve-chapter').forEach(b=>b.onclick=()=>approveChapter(b.dataset.id));document.querySelectorAll('.reject-chapter').forEach(b=>b.onclick=()=>setDocStatus('volunteer_chapter_requests',b.dataset.id,'rejected','chapter_rejected'));document.querySelectorAll('.delete-chapter').forEach(b=>b.onclick=()=>deleteChapter(b.dataset.id,b.dataset.active==='true'));document.querySelectorAll('.approve-care').forEach(b=>b.onclick=()=>setDocStatus('volunteer_care_projects',b.dataset.id,'approved','care_project_approved'));document.querySelectorAll('.reject-care').forEach(b=>b.onclick=()=>setDocStatus('volunteer_care_projects',b.dataset.id,'rejected','care_project_rejected'));document.querySelectorAll('.delete-record').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.col,b.dataset.id,b.dataset.label));document.querySelectorAll('.update-volunteer').forEach(b=>b.onclick=()=>openVolunteerEditModal(b.dataset.id));document.querySelectorAll('.assign-volunteer').forEach(b=>b.onclick=()=>quickAssignChapter(b.dataset.id));document.querySelectorAll('.assign-task').forEach(b=>b.onclick=()=>createAssignment(b.dataset.id));document.querySelectorAll('.delete-volunteer').forEach(b=>b.onclick=()=>deleteVolunteer(b.dataset.id));document.querySelectorAll('.copy-message').forEach(b=>b.onclick=()=>copyInviteMessage(b.dataset.id));}
function appCard(a){return `<article class="item"><span class="pill ${a.status==='accepted'?'ok':''}">${esc(a.status||'submitted')}</span><h3>${esc(a.name||'Applicant')}</h3><p>${esc(a.why||'No explanation provided.')}</p><div class="meta"><span>${esc(a.email||'')}</span><span>${esc(a.interest||'')}</span><span>Age: ${esc(a.age||'')}</span><span>${date(a.createdAt)}</span></div>${a.temporaryCode?`<div class="code-box">Activation Code: <strong>${esc(a.temporaryCode)}</strong></div>`:''}<div class="toolbar"><button class="btn primary accept-app" data-id="${a.id}">Accept / Generate Code</button>${a.temporaryCode?`<button class="btn copy-message" data-id="${a.id}">Copy Acceptance Message</button>`:''}<button class="btn reject-app" data-id="${a.id}">Reject</button><button class="btn danger delete-app" data-id="${a.id}">Delete</button></div></article>`;}
function chapterCard(c){return `<article class="item"><span class="pill ${c.status==='approved'?'ok':''}">Request: ${esc(c.status||'submitted')}</span><h3>${esc(c.chapterName||'Chapter Request')}</h3><p>${esc(c.purpose||'No purpose provided.')}</p><div class="meta"><span>${esc(c.email||'')}</span><span>${esc(c.chapterType||'')}</span><span>${esc(c.location||'')}</span></div><div class="toolbar"><button class="btn primary approve-chapter" data-id="${c.id}">Approve/Create Chapter</button><button class="btn reject-chapter" data-id="${c.id}">Reject</button><button class="btn danger delete-chapter" data-id="${c.id}" data-active="false">Delete</button></div></article>`;}
function activeChapterCard(c){return `<article class="item"><span class="pill ok">Active Chapter</span><h3>${esc(c.chapterName||c.name||'Chapter')}</h3><p>${esc(c.purpose||'')}</p><div class="meta"><span>ID: ${esc(c.chapterId||c.id)}</span><span>${esc(c.chapterType||'')}</span><span>${esc(c.location||'')}</span><span>Leader: ${esc(c.leaderEmail||c.email||'Unassigned')}</span></div><div class="toolbar"><button class="btn danger delete-chapter" data-id="${c.id}" data-active="true">Delete Active Chapter</button></div></article>`;}
function volunteerCard(v){return `<article class="item"><span class="pill ok">${esc(v.status||'Active')}</span><h3>${esc(v.name||v.email||'Volunteer')}</h3><p>${esc(v.team||'Prayer Support')} · ${esc(v.role||'Volunteer')}</p><div class="meta"><span>${esc(v.email||'')}</span><span>Chapter: ${esc(v.chapterId||'None')}</span><span>Agreement: ${v.agreementAccepted?'Yes':'No'}</span><span>Training: ${v.trainingCompleted?'Yes':'No'}</span></div><div class="toolbar"><button class="btn update-volunteer" data-id="${v.id}">Edit Profile</button><button class="btn assign-volunteer" data-id="${v.id}">Assign Chapter</button><button class="btn assign-task" data-id="${v.id}">Assign Task</button><button class="btn danger delete-volunteer" data-id="${v.id}">Delete Volunteer Record</button></div></article>`;}
function activityCard(a){return genericRecordCard('Activity','volunteer_activity_updates',a.id,a.name||a.email,a.summary,`${a.type||'Update'} · ${date(a.createdAt)}`)}
function serviceLogCard(a){return genericRecordCard('Service Log','volunteer_service_logs',a.id,a.name||a.email,a.summary,`${a.type||''} · ${a.minutes||0} minutes · ${a.date||''}`)}
function careProjectCard(a){return `<article class="item"><span class="pill ${a.status==='approved'?'ok':''}">Care Project: ${esc(a.status||'submitted')}</span><h3>${esc(a.title||'Project')}</h3><p>${esc(a.purpose||'')}</p><div class="meta"><span>${esc(a.name||a.email||'Volunteer')}</span><span>${esc(a.type||'')}</span></div><div class="toolbar"><button class="btn primary approve-care" data-id="${a.id}">Approve</button><button class="btn reject-care" data-id="${a.id}">Reject</button><button class="btn danger delete-record" data-col="volunteer_care_projects" data-id="${a.id}" data-label="care project">Delete</button></div></article>`;}
function trainingCard(a){return genericRecordCard('Training','volunteer_training_completions',a.id,a.name||a.email,a.reflection,date(a.createdAt))}
function assignmentCard(a){return genericRecordCard('Assignment','volunteer_assignments',a.id,a.title,a.description,`${a.assignedToEmail||''} · ${a.status||'open'} · ${a.priority||'normal'}`)}
function contactCard(a){return genericRecordCard('Contact','volunteer_contacts',a.id,a.subject,a.message,`${a.email||''} · ${a.type||''}`)}
function leaveCard(a){return genericRecordCard('Leave','volunteer_leave_requests',a.id,a.name||a.email,a.reason,`${a.startDate||''} to ${a.endDate||''} · ${a.status||'submitted'}`)}
function genericRecordCard(label,col,id,title,body,meta){return `<article class="item"><span class="pill">${esc(label)}</span><h3>${esc(title||label)}</h3><p>${esc(body||'')}</p><div class="meta"><span>${esc(meta||'')}</span></div><div class="toolbar"><button class="btn danger delete-record" data-col="${esc(col)}" data-id="${esc(id)}" data-label="${esc(label)}">Delete</button></div></article>`;}
function createProvisionModal(){if($('provisionModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="provision-modal" id="provisionModal"><div class="provision-backdrop" data-close-provision></div><section class="provision-card"><button class="provision-close" data-close-provision>×</button><p class="eyebrow">Account Provisioning</p><h2 id="provisionTitle">Accept Volunteer</h2><p class="muted">Emails are not automated right now. After generating a code, use Copy Acceptance Message and send it manually.</p><form id="provisionForm"><label>Team<select id="provTeam"><option>Prayer Support Team</option><option>Chapter Leadership Team</option><option>Care and Outreach Team</option><option>Administrative Support Team</option><option>Training and Onboarding Team</option></select></label><label>Role<input id="provRole" placeholder="Volunteer, Chapter Leader, Coordinator..."></label><label>Status<select id="provStatus"><option>Active</option><option>Training</option><option>Probationary</option><option>Limited</option><option>Suspended</option><option>Inactive</option></select></label><label>Chapter Assignment<select id="provChapterId"><option value="">No chapter assigned</option></select></label><label>Permissions<select id="provPermissions" multiple size="8"><option value="activity:create" selected>Submit Activity Updates</option><option value="service:log" selected>Submit Service Logs</option><option value="chapter:request" selected>Request Chapters</option><option value="chapter:lead">Lead Chapters</option><option value="outreach:create">Create Outreach Projects</option><option value="prayer:team">Prayer Team Access</option><option value="training:complete">Complete Training</option><option value="admin:limited">Limited Admin Assistance</option></select></label><button class="btn primary full" type="submit">Save / Generate Code</button><p class="notice" id="provisionNotice"></p></form></section></div>`);document.querySelectorAll('[data-close-provision]').forEach(x=>x.onclick=closeProvisionModal);$('provisionForm').onsubmit=submitProvision;}
let selectedApplication=null, selectedVolunteer=null;
function populateChapterSelect(value=''){const sel=$('provChapterId');if(!sel)return;sel.innerHTML='<option value="">No chapter assigned</option>'+approvedChapters.map(c=>`<option value="${esc(c.chapterId||c.id)}">${esc(c.chapterName||c.name||c.id)}</option>`).join('');sel.value=value||'';}
function openProvisionModal(id){selectedApplication=apps.find(x=>x.id===id);selectedVolunteer=null;if(!selectedApplication)return;$('provisionTitle').textContent='Accept '+(selectedApplication.name||'Volunteer');$('provRole').value=selectedApplication.interest||'Volunteer';$('provTeam').value=teamFromInterest(selectedApplication.interest);$('provStatus').value='Training';populateChapterSelect('');$('provisionNotice').textContent='';$('provisionModal').classList.add('show');}
function openVolunteerEditModal(id){selectedVolunteer=volunteers.find(x=>x.id===id);selectedApplication=null;if(!selectedVolunteer)return;$('provisionTitle').textContent='Edit '+(selectedVolunteer.name||'Volunteer');$('provRole').value=selectedVolunteer.role||'Volunteer';$('provTeam').value=selectedVolunteer.team||'Prayer Support Team';$('provStatus').value=selectedVolunteer.status||'Active';populateChapterSelect(selectedVolunteer.chapterId||'');$('provisionNotice').textContent='';$('provisionModal').classList.add('show');}
function closeProvisionModal(){$('provisionModal').classList.remove('show');selectedApplication=null;selectedVolunteer=null;}
async function submitProvision(e){e.preventDefault();const permissions=[...$('provPermissions').selectedOptions].map(o=>o.value),chapterId=$('provChapterId')?.value||'';try{if(selectedVolunteer){await updateDoc(doc(db,'volunteers',selectedVolunteer.id),{team:$('provTeam').value,role:$('provRole').value.trim()||'Volunteer',status:$('provStatus').value,permissions,chapterId,updatedAt:serverTimestamp(),updatedBy:auth.currentUser?.email||'Admin'});await audit('updated_volunteer_profile',selectedVolunteer.email||selectedVolunteer.id);closeProvisionModal();await loadAll();return;}if(!selectedApplication)return;const code=makeCode(),email=cleanEmail(selectedApplication.email);await setDoc(doc(db,'volunteer_invites',emailKey(email)),{email,emailKey:emailKey(email),name:selectedApplication.name||'',role:$('provRole').value.trim()||'Volunteer',team:$('provTeam').value,volunteerStatus:$('provStatus').value,permissions,chapterId,code,used:false,status:'active',applicationId:selectedApplication.id,createdAt:serverTimestamp(),createdBy:auth.currentUser?.email||'Admin'},{merge:true});await updateDoc(doc(db,'volunteer_applications',selectedApplication.id),{status:'accepted',acceptedAt:serverTimestamp(),temporaryCode:code,assignedRole:$('provRole').value.trim()||'Volunteer',assignedTeam:$('provTeam').value,assignedStatus:$('provStatus').value,assignedPermissions:permissions,assignedChapterId:chapterId,updatedAt:serverTimestamp()});await audit('accepted_volunteer_application',email);$('provisionNotice').textContent='One-time code generated: '+code;await loadAll();}catch(err){console.error(err);$('provisionNotice').textContent='Provisioning failed. Check Firestore rules.';$('provisionNotice').className='notice error';}}
async function approveChapter(id){const c=chapters.find(x=>x.id===id);if(!c)return;const chapterId=c.chapterId||('TPP-CH-'+id.slice(0,6).toUpperCase());await updateDoc(doc(db,'volunteer_chapter_requests',id),{status:'approved',chapterId,updatedAt:serverTimestamp(),approvedBy:auth.currentUser?.email||'Admin'});await setDoc(doc(db,'volunteer_chapters',chapterId),{...c,sourceRequestId:id,chapterId,status:'active',leaderEmail:c.email||'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});await audit('chapter_approved_created',chapterId);await loadAll();}
async function deleteChapter(id,active){if(!confirm('Delete this chapter/chapter request?'))return;await deleteDoc(doc(db,active?'volunteer_chapters':'volunteer_chapter_requests',id));if(!active)try{await deleteDoc(doc(db,'volunteer_chapters',id));}catch(e){}await audit('deleted_chapter',id);await loadAll();}
async function quickAssignChapter(id){const v=volunteers.find(x=>x.id===id);if(!v)return;const list=approvedChapters.map(c=>`${c.chapterId||c.id} - ${c.chapterName||c.name||'Chapter'}`).join('\n');const chapterId=prompt('Enter Chapter ID to assign:\n\n'+(list||'No active chapters yet.'),v.chapterId||'');if(chapterId===null)return;await updateDoc(doc(db,'volunteers',id),{chapterId:chapterId.trim(),updatedAt:serverTimestamp(),updatedBy:auth.currentUser?.email||'Admin'});await audit('assigned_chapter',`${v.email||id}:${chapterId}`);await loadAll();}
async function createAssignment(id){const v=volunteers.find(x=>x.id===id);if(!v)return;const title=prompt('Assignment title:');if(!title)return;const description=prompt('Assignment description:')||'';const priority=prompt('Priority:', 'normal')||'normal';await addDoc(collection(db,'volunteer_assignments'),{title,description,priority,status:'open',assignedToUid:id,assignedToEmail:v.email||'',assignedToName:v.name||'',assignedBy:auth.currentUser?.email||'Admin',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('created_assignment',v.email||id);await loadAll();}
async function setDocStatus(col,id,status,auditName){await updateDoc(doc(db,col,id),{status,updatedAt:serverTimestamp(),reviewedBy:auth.currentUser?.email||'Admin'});await audit(auditName,id);await loadAll();}
async function deleteApplication(id){const app=apps.find(a=>a.id===id);if(!confirm('Delete this application permanently?'))return;await deleteDoc(doc(db,'volunteer_applications',id));if(app?.email)try{await deleteDoc(doc(db,'volunteer_invites',emailKey(app.email)));}catch(e){}await audit('deleted_application',id);await loadAll();}
async function deleteVolunteer(id){const v=volunteers.find(x=>x.id===id);if(!confirm('Delete this volunteer record? This removes the Firestore volunteer profile but not the Firebase Auth user.'))return;await deleteDoc(doc(db,'volunteers',id));await audit('deleted_volunteer_record',v?.email||id);await loadAll();}
async function deleteRecord(col,id,label){if(!confirm('Delete this '+(label||'record')+'?'))return;await deleteDoc(doc(db,col,id));await audit('deleted_'+col,id);await loadAll();}
function copyInviteMessage(id){const a=apps.find(x=>x.id===id);if(!a)return;const msg=`Hello ${a.name||'there'},\n\nYour volunteer application for The Prayer Project has been accepted.\n\nUse this temporary one-time code to activate your account:\n${a.temporaryCode||''}\n\nActivation page:\nhttps://volunteer.ask4prayers.com/login.html\n\nThis code is user-specific and can only be used once. After activation, you will be able to access the volunteer portal.\n\nThank you for being willing to serve.\nThe Prayer Project Volunteer Network`;navigator.clipboard?.writeText(msg);alert('Acceptance message copied. Send it manually because email automation is not active.');}
async function audit(action,target){try{await addDoc(collection(db,'audit_logs'),{action,requestId:'volunteer:'+target,adminEmail:auth.currentUser?.email||'Admin',createdAt:serverTimestamp()});}catch(e){console.warn(e);}}
function injectAdminLogin(){document.body.insertAdjacentHTML('beforeend',`<div id="adminGate" class="admin-gate"><form id="adminLogin" class="card"><p class="eyebrow">Admin Login</p><h2>Volunteer Admin</h2><label>Email<input id="adminEmail" type="email" required></label><label>Password<input id="adminPassword" type="password" required></label><button class="btn primary full">Sign In</button><p class="notice" id="adminNotice"></p></form></div>`);$('adminLogin').addEventListener('submit',async e=>{e.preventDefault();try{$('adminNotice').textContent='Signing in...';await signInWithEmailAndPassword(auth,$('adminEmail').value.trim(),$('adminPassword').value);}catch(err){$('adminNotice').textContent='Login failed.';$('adminNotice').className='notice error';}});const logout=document.createElement('button');logout.className='btn';logout.textContent='Sign Out';logout.onclick=()=>signOut(auth);document.querySelector('.nav-links')?.appendChild(logout);}
function showLogin(){$('adminGate').classList.add('show')}function hideLogin(){$('adminGate').classList.remove('show')}
function injectAdminStyles(){if($('adminExtraStyles'))return;const style=document.createElement('style');style.id='adminExtraStyles';style.textContent=`.item{padding:18px;border:1px solid var(--line);border-radius:22px;background:rgba(255,255,255,.045)}.item h3{margin:10px 0}.meta,.toolbar{display:flex;gap:10px;flex-wrap:wrap}.meta{color:var(--soft);font-size:13px}.code-box{padding:12px;border:1px solid rgba(159,242,179,.25);border-radius:16px;color:var(--green);background:rgba(159,242,179,.08);margin-top:12px}.btn.danger,.danger{border-color:rgba(255,209,209,.28)!important;color:var(--danger)!important}.admin-gate{display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.88);backdrop-filter:blur(14px);align-items:center;justify-content:center;padding:20px}.admin-gate.show{display:flex}.admin-gate .card{width:min(480px,100%)}.provision-modal{position:fixed;inset:0;z-index:9998;display:none;align-items:center;justify-content:center;padding:20px}.provision-modal.show{display:flex}.provision-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.82);backdrop-filter:blur(12px)}.provision-card{position:relative;width:min(620px,100%);max-height:calc(100vh - 40px);overflow:auto;padding:30px;border-radius:30px;background:#090807;border:1px solid var(--line);box-shadow:0 35px 120px rgba(0,0,0,.85)}.provision-close{position:absolute;right:16px;top:16px;border:1px solid var(--line);background:rgba(255,255,255,.06);color:var(--text);border-radius:50%;width:38px;height:38px;font-size:22px}.pill{display:inline-flex;padding:7px 10px;border-radius:999px;background:rgba(216,195,165,.08);border:1px solid var(--line);color:var(--warm2);font-size:11px;font-weight:900;text-transform:uppercase}.pill.ok{color:var(--green);border-color:rgba(159,242,179,.25)}.stat strong{display:block;font-size:38px;color:var(--warm2)}`;document.head.appendChild(style);}
function teamFromInterest(i=''){return i.includes('Chapter')?'Chapter Leadership Team':i.includes('Local')?'Care and Outreach Team':i.includes('Admin')?'Administrative Support Team':i.includes('Encouragement')?'Care and Outreach Team':'Prayer Support Team'}
function makeCode(){return 'TPP-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}function setText(id,t){const el=$(id);if(el)el.textContent=t}function cleanEmail(e=''){return String(e).trim().toLowerCase()}function emailKey(e=''){return cleanEmail(e).replace(/[.#$/\[\]]/g,'_')}function date(t){return t?.toDate?t.toDate().toLocaleString():'Recently'}function esc(t=''){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}