import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js";
import { getFirestore, collection, getDocs, query, orderBy, doc, updateDoc, setDoc, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyAaaABQB1T_SaZ6TARafIXjJ6Zk-upjLO0",authDomain:"prayer-projec.firebaseapp.com",projectId:"prayer-projec",storageBucket:"prayer-projec.firebasestorage.app",messagingSenderId:"47966669764",appId:"1:47966669764:web:b875d2ea5bf75e3b7b3291"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
let apps=[],chapters=[],volunteers=[],activities=[];

injectAdminStyles();
injectAdminLogin();
createProvisionModal();
onAuthStateChanged(auth,async user=>{if(!user){showLogin();return;}hideLogin();await loadAll();});

async function loadAll(){try{const [a,c,v,u]=await Promise.all([getDocs(query(collection(db,'volunteer_applications'),orderBy('createdAt','desc'))),getDocs(query(collection(db,'volunteer_chapter_requests'),orderBy('createdAt','desc'))),getDocs(collection(db,'volunteers')),getDocs(query(collection(db,'volunteer_activity_updates'),orderBy('createdAt','desc')))]);apps=[];chapters=[];volunteers=[];activities=[];a.forEach(d=>apps.push({id:d.id,...d.data()}));c.forEach(d=>chapters.push({id:d.id,...d.data()}));v.forEach(d=>volunteers.push({id:d.id,...d.data()}));u.forEach(d=>activities.push({id:d.id,...d.data()}));render();}catch(e){console.error(e);$('applicationList').innerHTML='Could not load volunteer records. Check Firestore rules.';}}
function render(){setText('appCount',apps.length);setText('chapterCount',chapters.length);setText('volunteerCount',volunteers.length);$('applicationList').innerHTML=apps.length?apps.map(appCard).join(''):'<div>No applications yet.</div>';$('chapterList').innerHTML=chapters.length?chapters.map(chapterCard).join(''):'<div>No chapter requests yet.</div>';if($('volunteerList'))$('volunteerList').innerHTML=volunteers.length?volunteers.map(volunteerCard).join(''):'<div>No volunteers activated yet.</div>';$('activityList').innerHTML=activities.length?activities.map(activityCard).join(''):'<div>No activity updates yet.</div>';document.querySelectorAll('.accept-app').forEach(b=>b.onclick=()=>openProvisionModal(b.dataset.id));document.querySelectorAll('.reject-app').forEach(b=>b.onclick=()=>setApplicationStatus(b.dataset.id,'rejected'));document.querySelectorAll('.approve-chapter').forEach(b=>b.onclick=()=>setChapterStatus(b.dataset.id,'approved'));document.querySelectorAll('.reject-chapter').forEach(b=>b.onclick=()=>setChapterStatus(b.dataset.id,'rejected'));document.querySelectorAll('.update-volunteer').forEach(b=>b.onclick=()=>openVolunteerEditModal(b.dataset.id));}
function appCard(a){return `<article class="item"><span class="pill ${a.status==='accepted'?'ok':''}">${esc(a.status||'submitted')}</span><h3>${esc(a.name||'Applicant')}</h3><p>${esc(a.why||'No explanation provided.')}</p><div class="meta"><span>${esc(a.email||'')}</span><span>${esc(a.interest||'')}</span><span>Age: ${esc(a.age||'')}</span><span>${date(a.createdAt)}</span></div>${a.temporaryCode?`<div class="code-box">Activation Code: <strong>${esc(a.temporaryCode)}</strong></div>`:''}<div class="toolbar"><button class="btn primary accept-app" data-id="${a.id}">Accept / Generate Code</button><button class="btn reject-app" data-id="${a.id}">Reject</button></div></article>`;}
function chapterCard(c){return `<article class="item"><span class="pill ${c.status==='approved'?'ok':''}">${esc(c.status||'submitted')}</span><h3>${esc(c.chapterName||'Chapter Request')}</h3><p>${esc(c.purpose||'No purpose provided.')}</p><div class="meta"><span>${esc(c.email||'')}</span><span>${esc(c.chapterType||'')}</span><span>${esc(c.location||'')}</span></div><div class="toolbar"><button class="btn primary approve-chapter" data-id="${c.id}">Approve</button><button class="btn reject-chapter" data-id="${c.id}">Reject</button></div></article>`;}
function volunteerCard(v){return `<article class="item"><span class="pill ok">${esc(v.status||'Active')}</span><h3>${esc(v.name||v.email||'Volunteer')}</h3><p>${esc(v.team||'Prayer Support')} · ${esc(v.role||'Volunteer')}</p><div class="meta"><span>${esc(v.email||'')}</span><span>${Array.isArray(v.permissions)?esc(v.permissions.join(', ')):esc(v.permissions||'Standard')}</span></div><div class="toolbar"><button class="btn update-volunteer" data-id="${v.id}">Edit Profile</button></div></article>`;}
function activityCard(a){return `<article class="item"><span class="pill">${esc(a.type||'Update')}</span><h3>${esc(a.name||a.email||'Volunteer')}</h3><p>${esc(a.summary||'')}</p><div class="meta"><span>${esc(a.email||'')}</span><span>${date(a.createdAt)}</span></div></article>`;}
function createProvisionModal(){if($('provisionModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="provision-modal" id="provisionModal"><div class="provision-backdrop" data-close-provision></div><section class="provision-card"><button class="provision-close" data-close-provision>×</button><p class="eyebrow">Account Provisioning</p><h2 id="provisionTitle">Accept Volunteer</h2><p class="muted">Set the volunteer status, team, role, and permissions. A user-specific one-time code will be generated for this email only.</p><form id="provisionForm"><label>Team<select id="provTeam"><option>Prayer Support Team</option><option>Chapter Leadership Team</option><option>Care and Outreach Team</option><option>Administrative Support Team</option><option>Training and Onboarding Team</option></select></label><label>Role<input id="provRole" placeholder="Volunteer, Chapter Leader, Coordinator..."></label><label>Status<select id="provStatus"><option>Active</option><option>Training</option><option>Probationary</option><option>Limited</option></select></label><label>Permissions<select id="provPermissions" multiple size="6"><option value="activity:create" selected>Submit Activity Updates</option><option value="chapter:request" selected>Request Chapters</option><option value="chapter:lead">Lead Chapters</option><option value="outreach:create">Create Outreach Projects</option><option value="prayer:team">Prayer Team Access</option><option value="admin:limited">Limited Admin Assistance</option></select></label><button class="btn primary full" type="submit">Accept and Generate One-Time Code</button><p class="notice" id="provisionNotice"></p></form></section></div>`);document.querySelectorAll('[data-close-provision]').forEach(x=>x.onclick=closeProvisionModal);$('provisionForm').onsubmit=submitProvision;}
let selectedApplication=null, selectedVolunteer=null;
function openProvisionModal(id){selectedApplication=apps.find(x=>x.id===id);selectedVolunteer=null;if(!selectedApplication)return;$('provisionTitle').textContent='Accept '+(selectedApplication.name||'Volunteer');$('provRole').value=selectedApplication.interest||'Volunteer';$('provTeam').value=teamFromInterest(selectedApplication.interest);$('provStatus').value='Training';$('provisionNotice').textContent='';$('provisionModal').classList.add('show');}
function openVolunteerEditModal(id){selectedVolunteer=volunteers.find(x=>x.id===id);selectedApplication=null;if(!selectedVolunteer)return;$('provisionTitle').textContent='Edit '+(selectedVolunteer.name||'Volunteer');$('provRole').value=selectedVolunteer.role||'Volunteer';$('provTeam').value=selectedVolunteer.team||'Prayer Support Team';$('provStatus').value=selectedVolunteer.status||'Active';$('provisionNotice').textContent='';$('provisionModal').classList.add('show');}
function closeProvisionModal(){$('provisionModal').classList.remove('show');selectedApplication=null;selectedVolunteer=null;}
async function submitProvision(e){e.preventDefault();const permissions=[...$('provPermissions').selectedOptions].map(o=>o.value);try{if(selectedVolunteer){await updateDoc(doc(db,'volunteers',selectedVolunteer.id),{team:$('provTeam').value,role:$('provRole').value.trim()||'Volunteer',status:$('provStatus').value,permissions,updatedAt:serverTimestamp(),updatedBy:auth.currentUser?.email||'Admin'});await audit('updated_volunteer_profile',selectedVolunteer.email||selectedVolunteer.id);closeProvisionModal();await loadAll();return;}if(!selectedApplication)return;const code=makeCode(),email=cleanEmail(selectedApplication.email);await setDoc(doc(db,'volunteer_invites',emailKey(email)),{email,emailKey:emailKey(email),name:selectedApplication.name||'',role:$('provRole').value.trim()||'Volunteer',team:$('provTeam').value,volunteerStatus:$('provStatus').value,permissions,code,used:false,status:'active',applicationId:selectedApplication.id,createdAt:serverTimestamp(),createdBy:auth.currentUser?.email||'Admin'},{merge:true});await updateDoc(doc(db,'volunteer_applications',selectedApplication.id),{status:'accepted',acceptedAt:serverTimestamp(),temporaryCode:code,assignedRole:$('provRole').value.trim()||'Volunteer',assignedTeam:$('provTeam').value,assignedStatus:$('provStatus').value,assignedPermissions:permissions,updatedAt:serverTimestamp()});await audit('accepted_volunteer_application',email);$('provisionNotice').textContent='One-time code generated: '+code;setTimeout(closeProvisionModal,1200);await loadAll();}catch(err){console.error(err);$('provisionNotice').textContent='Provisioning failed. Check Firestore rules.';$('provisionNotice').className='notice error';}}
async function setApplicationStatus(id,status){await updateDoc(doc(db,'volunteer_applications',id),{status,updatedAt:serverTimestamp()});await audit('application_'+status,id);await loadAll();}
async function setChapterStatus(id,status){await updateDoc(doc(db,'volunteer_chapter_requests',id),{status,updatedAt:serverTimestamp()});await audit('chapter_'+status,id);await loadAll();}
async function audit(action,target){try{await addDoc(collection(db,'audit_logs'),{action,requestId:'volunteer:'+target,adminEmail:auth.currentUser?.email||'Admin',createdAt:serverTimestamp()});}catch(e){console.warn(e);}}
function injectAdminLogin(){document.body.insertAdjacentHTML('beforeend',`<div id="adminGate" class="admin-gate"><form id="adminLogin" class="card"><p class="eyebrow">Admin Login</p><h2>Volunteer Admin</h2><label>Email<input id="adminEmail" type="email" required></label><label>Password<input id="adminPassword" type="password" required></label><button class="btn primary full">Sign In</button><p class="notice" id="adminNotice"></p></form></div>`);$('adminLogin').addEventListener('submit',async e=>{e.preventDefault();try{$('adminNotice').textContent='Signing in...';await signInWithEmailAndPassword(auth,$('adminEmail').value.trim(),$('adminPassword').value);}catch(err){$('adminNotice').textContent='Login failed.';$('adminNotice').className='notice error';}});const logout=document.createElement('button');logout.className='btn';logout.textContent='Sign Out';logout.onclick=()=>signOut(auth);document.querySelector('.nav-links')?.appendChild(logout);}
function showLogin(){$('adminGate').classList.add('show')}function hideLogin(){$('adminGate').classList.remove('show')}
function injectAdminStyles(){if($('adminExtraStyles'))return;const style=document.createElement('style');style.id='adminExtraStyles';style.textContent=`.item{padding:18px;border:1px solid var(--line);border-radius:22px;background:rgba(255,255,255,.045)}.item h3{margin:10px 0}.meta,.toolbar{display:flex;gap:10px;flex-wrap:wrap}.meta{color:var(--soft);font-size:13px}.code-box{padding:12px;border:1px solid rgba(159,242,179,.25);border-radius:16px;color:var(--green);background:rgba(159,242,179,.08);margin-top:12px}.admin-gate{display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.88);backdrop-filter:blur(14px);align-items:center;justify-content:center;padding:20px}.admin-gate.show{display:flex}.admin-gate .card{width:min(480px,100%)}.provision-modal{position:fixed;inset:0;z-index:9998;display:none;align-items:center;justify-content:center;padding:20px}.provision-modal.show{display:flex}.provision-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.82);backdrop-filter:blur(12px)}.provision-card{position:relative;width:min(620px,100%);max-height:calc(100vh - 40px);overflow:auto;padding:30px;border-radius:30px;background:#090807;border:1px solid var(--line);box-shadow:0 35px 120px rgba(0,0,0,.85)}.provision-close{position:absolute;right:16px;top:16px;border:1px solid var(--line);background:rgba(255,255,255,.06);color:var(--text);border-radius:50%;width:38px;height:38px;font-size:22px}.pill{display:inline-flex;padding:7px 10px;border-radius:999px;background:rgba(216,195,165,.08);border:1px solid var(--line);color:var(--warm2);font-size:11px;font-weight:900;text-transform:uppercase}.pill.ok{color:var(--green);border-color:rgba(159,242,179,.25)}.stat strong{display:block;font-size:38px;color:var(--warm2)}`;document.head.appendChild(style);}
function teamFromInterest(i=''){return i.includes('Chapter')?'Chapter Leadership Team':i.includes('Local')?'Care and Outreach Team':i.includes('Admin')?'Administrative Support Team':i.includes('Encouragement')?'Care and Outreach Team':'Prayer Support Team'}
function makeCode(){return 'TPP-'+Math.random().toString(36).slice(2,6).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}function setText(id,t){const el=$(id);if(el)el.textContent=t}function cleanEmail(e=''){return String(e).trim().toLowerCase()}function emailKey(e=''){return cleanEmail(e).replace(/[.#$/\[\]]/g,'_')}function date(t){return t?.toDate?t.toDate().toLocaleString():'Recently'}function esc(t=''){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}