import {getApps,getApp} from 'https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js';
import {getFirestore,collection,getDocs,query,where,limit,doc,getDoc,addDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js';

const app=getApps().length?getApp():null, auth=app?getAuth(app):null, db=app?getFirestore(app):null;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const date=v=>{try{return (v?.toDate?v.toDate():new Date(v)).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}catch{return 'Date to be announced'}};
const read=async(name,max=12)=>{try{const s=await getDocs(query(collection(db,name),limit(max))),a=[];s.forEach(d=>a.push({id:d.id,...d.data()}));return a}catch{return[]}};
const readMine=async(name,field,value,max=30)=>{try{const s=await getDocs(query(collection(db,name),where(field,'==',value),limit(max))),a=[];s.forEach(d=>a.push({id:d.id,...d.data()}));return a}catch{return[]}};

if(auth&&db) onAuthStateChanged(auth,async user=>{if(!user||!document.getElementById('dashboard'))return;const s=await getDoc(doc(db,'volunteers',user.uid));if(!s.exists())return;await buildPortal(user,{id:user.uid,...s.data()})});

async function buildPortal(user,v){
 const root=document.getElementById('dashboard');
 const [opportunities,events,announcements,logs,assignments,resources]=await Promise.all([read('volunteer_opportunities'),read('volunteer_events'),read('volunteer_announcements',6),readMine('volunteer_service_logs','uid',user.uid),readMine('volunteer_assignments','assignedToUid',user.uid),read('volunteer_resources',8)]);
 const approved=logs.filter(x=>/approved/i.test(x.approvalStatus||x.status||''));
 const hours=(approved.reduce((n,x)=>n+Number(x.minutes||0),0)/60).toFixed(1);
 const activeAssignments=assignments.filter(x=>!/complete|closed/i.test(x.status||''));
 const next=nextStep(v,activeAssignments,opportunities);
 document.querySelectorAll('.dashboard > *').forEach(el=>el.classList.add('v3-hidden-legacy'));
 root.insertAdjacentHTML('afterbegin',`<nav class="v3-program-nav"><a class="active" href="#home">Home</a><a href="#opportunities">Opportunities</a><a href="#schedule">Schedule</a><a href="training.html">Training</a><a href="#service">My Service</a><a href="#team">My Team</a><a href="#resources">Resources</a><a href="contact.html">Help</a></nav><div class="v3-shell" id="home">
 <section class="v3-hero"><article class="v3-welcome"><span class="v3-kicker">The Prayer Project Volunteer Network</span><h1>Welcome back, ${esc(v.preferredName||v.name?.split(' ')[0]||'Volunteer')}.</h1><p>You came here because you wanted to serve. We’ll make everything else easy.</p></article><article class="v3-next"><div><span class="v3-kicker">Your next step</span><h2>${esc(next.title)}</h2><p>${esc(next.text)}</p></div><a class="btn primary" href="${next.href}">${esc(next.action)}</a></article></section>
 <section class="v3-stats"><article class="v3-stat"><strong>${esc(v.status||'Onboarding')}</strong><span>VOLUNTEER STATUS</span></article><article class="v3-stat"><strong>${hours}</strong><span>VERIFIED HOURS</span></article><article class="v3-stat"><strong>${approved.length}</strong><span>SERVICE RECORDS</span></article><article class="v3-stat"><strong>${activeAssignments.length}</strong><span>OPEN ASSIGNMENTS</span></article></section>
 <div class="v3-layout"><div><section class="v3-section" id="opportunities"><div class="v3-section-head"><div><span class="v3-kicker">Where you’re needed</span><h2>Service opportunities</h2></div></div><div class="v3-opportunities">${renderOpportunities(opportunities,v)}</div></section><section class="v3-section" id="schedule"><div class="v3-section-head"><div><span class="v3-kicker">Coming up</span><h2>Your schedule</h2></div></div><div class="v3-list">${renderEvents(events,activeAssignments)}</div></section><section class="v3-section" id="service"><div class="v3-section-head"><div><span class="v3-kicker">Permanent record</span><h2>My service</h2></div><a class="btn" href="#legacyService" id="openServiceForm">Add outside service</a></div><div class="v3-list">${renderLogs(logs)}</div></section></div>
 <aside><section class="v3-section" id="team"><span class="v3-kicker">Your people</span><h2>${esc(v.team||'Placement pending')}</h2><p>${esc(v.teamLeadName?`Team Lead: ${v.teamLeadName}`:'Leadership will connect you with your Team Lead.')}</p><div class="v3-meta"><span class="v3-pill green">${esc(v.role||'Volunteer')}</span><span class="v3-pill">${esc(v.volunteerId||'ID pending')}</span></div></section><section class="v3-section"><span class="v3-kicker">Updates</span><h2>Announcements</h2><div class="v3-list">${renderAnnouncements(announcements)}</div></section><section class="v3-section" id="resources"><span class="v3-kicker">Useful now</span><h2>Quick access</h2><div class="v3-quick"><a href="training.html">Volunteer Academy</a><a href="handbook.html">Handbook</a><a href="contact.html">Report a Concern</a><a href="leave.html">Request Leave</a>${resources.slice(0,4).map(r=>`<a href="${esc(r.url||'#')}" target="_blank" rel="noopener">${esc(r.title||'Resource')}</a>`).join('')}</div></section></aside></div></div>`);
 document.getElementById('openServiceForm')?.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('.dashboard > *').forEach(el=>el.classList.remove('v3-hidden-legacy'));document.querySelector('.v3-shell')?.scrollIntoView({behavior:'smooth',block:'end'})});
 document.querySelectorAll('[data-request-opportunity]').forEach(b=>b.addEventListener('click',()=>requestOpportunity(b,user,v)));
}
function nextStep(v,assignments,ops){if(!v.agreementAccepted)return{title:'Accept the Volunteer Agreement',text:'Review the handbook and confirm the standards that protect volunteers and the people we serve.',href:'handbook.html',action:'Review standards'};if(!v.trainingCompleted)return{title:'Complete Core Orientation',text:'Finish safety, confidentiality, boundaries, representation, and incident training.',href:'training.html',action:'Continue training'};if(assignments.length)return{title:assignments[0].title||'Review your assignment',text:assignments[0].description||'Leadership has work ready for you.',href:'assignments.html',action:'View assignment'};if(ops.length)return{title:'Choose where to serve',text:'Your onboarding is complete. Find an opportunity that fits your team and availability.',href:'#opportunities',action:'See opportunities'};return{title:'You’re ready to serve',text:'No open opportunities are posted right now. Check announcements or contact your Team Lead.',href:'contact.html',action:'Contact leadership'}}
function renderOpportunities(rows,v){const open=rows.filter(x=>!/closed|cancel/i.test(x.status||''));if(!open.length)return'<div class="v3-empty"><strong>No open opportunities right now.</strong><br>Leadership will post new ways to serve here.</div>';return open.slice(0,6).map(x=>`<article class="v3-opportunity"><h3>${esc(x.title||'Service Opportunity')}</h3><p>${esc(x.description||'Details will be provided by leadership.')}</p><div class="v3-meta"><span class="v3-pill green">${esc(x.team||x.audience||'All Teams')}</span><span class="v3-pill">${esc(x.location||'Location TBA')}</span>${x.minimumAge?`<span class="v3-pill">Age ${esc(x.minimumAge)}+</span>`:''}</div><button class="btn primary" data-request-opportunity="${esc(x.id)}">Request to serve</button></article>`).join('')}
function renderEvents(events,assignments){const all=[...events.map(x=>({...x,kind:'Event'})),...assignments.map(x=>({...x,kind:'Assignment'}))];if(!all.length)return'<div class="v3-empty">Nothing is scheduled yet.</div>';return all.slice(0,8).map(x=>`<article class="v3-list-item"><strong>${esc(x.title||x.name||x.kind)}</strong><small>${esc(x.kind)} · ${date(x.startAt||x.date||x.dueAt)} · ${esc(x.location||x.status||'Details pending')}</small></article>`).join('')}
function renderLogs(rows){if(!rows.length)return'<div class="v3-empty">Your service history will appear here after your first activity.</div>';return rows.slice(0,8).map(x=>`<article class="v3-list-item"><strong>${esc(x.type||'Volunteer Service')} · ${(Number(x.minutes||0)/60).toFixed(1)} hours</strong><small>${esc(x.date||'')} · ${esc(x.approvalStatus||x.status||'Pending Review')}</small></article>`).join('')}
function renderAnnouncements(rows){if(!rows.length)return'<div class="v3-empty">No announcements.</div>';return rows.map(x=>`<article class="v3-list-item"><strong>${esc(x.title||'Update')}</strong><small>${esc(x.message||x.body||'')}</small></article>`).join('')}
async function requestOpportunity(button,user,v){button.disabled=true;const old=button.textContent;try{await addDoc(collection(db,'volunteer_opportunity_requests'),{opportunityId:button.dataset.requestOpportunity,uid:user.uid,name:v.name||'',email:user.email||'',status:'requested',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});button.textContent='Request sent'}catch{button.disabled=false;button.textContent=old;alert('The request could not be sent. Leadership may need to publish the updated shared Firestore rules.')}}

