import { initializeApp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-auth.js";
import { getFirestore, collection, getDocs, doc, getDoc, setDoc, updateDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.12.1/firebase-firestore.js";
import { getAccessProfile } from "./access-control.js";

const firebaseConfig={apiKey:"AIzaSyAaaABQB1T_SaZ6TARafIXjJ6Zk-upjLO0",authDomain:"prayer-projec.firebaseapp.com",projectId:"prayer-projec",storageBucket:"prayer-projec.firebasestorage.app",messagingSenderId:"47966669764",appId:"1:47966669764:web:b875d2ea5bf75e3b7b3291"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let volunteers=[],trainers=[],selected=null,currentPlan=null,currentAccess=null;
const STANDARD_SECTIONS=[
  {id:'mission',title:'Mission and Heart of Service',description:'Understands why The Prayer Project serves through prayer, encouragement, privacy, and care.',active:true,completed:false},
  {id:'privacy',title:'Privacy and Request Handling',description:'Understands confidentiality, respectful handling of requests, and limits on sharing details.',active:true,completed:false},
  {id:'crisis',title:'Crisis Boundaries',description:'Understands that volunteers are not counselors or emergency responders and must direct crisis needs to proper resources.',active:true,completed:false},
  {id:'chapters',title:'Chapter Standards',description:'Understands how chapters work, reporting expectations, leadership approval, and chapter conduct.',active:false,completed:false},
  {id:'care-projects',title:'Care Project Standards',description:'Understands how to propose, document, and complete care projects safely and professionally.',active:false,completed:false},
  {id:'service-logs',title:'Service Logs and Accountability',description:'Understands how to document service honestly and consistently.',active:true,completed:false},
  {id:'communication',title:'Communication with Leadership',description:'Understands how to contact leadership, ask questions, report concerns, and request leave.',active:true,completed:false},
  {id:'final-review',title:'Final Trainer Review',description:'Trainer confirms the volunteer is ready for active service or recommends more training.',active:true,completed:false}
];

injectLogin();
onAuthStateChanged(auth,async user=>{if(!user){showLogin();return;}currentAccess=await getAccessProfile(user);if(!currentAccess.trainer){hideLogin();lockTrainerPage('You do not have verified trainer permission for this console.');return;}hideLogin();await loadData();});
$('loadTrainingBtn')?.addEventListener('click',openSelectedPlan);
$('resetTrainingBtn')?.addEventListener('click',resetPlan);
$('saveTrainingBtn')?.addEventListener('click',savePlan);

function lockTrainerPage(message){document.querySelector('main')?.insertAdjacentHTML('afterbegin',`<section class="shell dashboard"><div class="panel"><p class="eyebrow">Access Restricted</p><h1>Trainer access required.</h1><p class="lead">${esc(message)}</p><button class="btn" id="trainerLockLogout">Sign Out</button></div></section>`);document.getElementById('trainingWorkspace')?.remove();document.getElementById('loadTrainingBtn')?.setAttribute('disabled','true');document.getElementById('resetTrainingBtn')?.setAttribute('disabled','true');document.getElementById('trainerLockLogout')?.addEventListener('click',()=>signOut(auth));}
async function loadData(){try{const v=await getDocs(collection(db,'volunteers'));volunteers=[];trainers=[];v.forEach(d=>{const data={id:d.id,...d.data()};volunteers.push(data);const perms=Array.isArray(data.permissions)?data.permissions:[];if(perms.includes('training:trainer')||perms.includes('admin:limited'))trainers.push(data);});if(currentAccess?.owner&&!trainers.some(t=>t.email===auth.currentUser.email))trainers.unshift({id:auth.currentUser.uid,name:auth.currentUser.email,email:auth.currentUser.email,role:'Owner / Verified Trainer'});if(!currentAccess?.admin){trainers=trainers.filter(t=>t.id===auth.currentUser.uid||String(t.email||'').toLowerCase()===String(auth.currentUser.email||'').toLowerCase());}
renderSelectors();setText('traineeCount',volunteers.length);setText('trainerCount',trainers.length);const plans=await getDocs(collection(db,'volunteer_training_plans'));let count=0;plans.forEach(()=>count++);setText('activePlanCount',count);}catch(e){console.error(e);$('trainerNotice').textContent='Could not load trainer data. Check Firestore rules.';$('trainerNotice').className='notice error';}}
function renderSelectors(){const trainee=$('traineeSelect');trainee.innerHTML='<option value="">Select a volunteer...</option>'+volunteers.map(v=>`<option value="${esc(v.id)}">${esc(v.name||v.email)} — ${esc(v.status||'Status Unknown')}</option>`).join('');const trainer=$('assignedTrainerSelect');trainer.innerHTML=trainers.map(t=>`<option value="${esc(t.id)}">${esc(t.name||t.email)} — ${esc(t.role||'Trainer')}</option>`).join('');}
async function openSelectedPlan(){const id=$('traineeSelect').value;if(!id){notice('Select a volunteer first.','error');return;}selected=volunteers.find(v=>v.id===id);if(!selected)return;const snap=await getDoc(doc(db,'volunteer_training_plans',id));currentPlan=snap.exists()?snap.data():{uid:id,email:selected.email||'',name:selected.name||selected.email||'',assignedTrainerUid:auth.currentUser.uid,assignedTrainerEmail:auth.currentUser.email,status:'Assigned',sections:STANDARD_SECTIONS,notes:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};if(!currentAccess?.admin&&currentPlan.assignedTrainerUid&&currentPlan.assignedTrainerUid!==auth.currentUser.uid){notice('Only the assigned trainer or an admin can edit this training plan.','error');return;}renderPlan();}
function renderPlan(){if(!selected||!currentPlan)return;$('trainingWorkspace').style.display='block';$('selectedVolunteerName').textContent=selected.name||selected.email||'Volunteer';$('selectedVolunteerMeta').textContent=`${selected.email||''} · ${selected.team||'No team'} · ${selected.role||'Volunteer'} · ${selected.status||'No status'}`;$('assignedTrainerSelect').value=currentPlan.assignedTrainerUid||auth.currentUser.uid;if(!currentAccess?.admin)$('assignedTrainerSelect').disabled=true;$('trainingStatusSelect').value=currentPlan.status||'Assigned';$('trainerNotes').value=currentPlan.notes||'';const sections=Array.isArray(currentPlan.sections)?currentPlan.sections:STANDARD_SECTIONS;$('trainingSectionList').innerHTML=sections.map((s,i)=>`<div class="training-row"><div><strong>${esc(s.title)}</strong><p>${esc(s.description||'')}</p><span class="pill ${s.completed?'ok':''}">${s.completed?'Completed':s.active?'Active':'Inactive'}</span></div><div class="toolbar"><button class="btn toggle-active" data-index="${i}">${s.active?'Deactivate':'Activate'}</button><button class="btn primary toggle-complete" data-index="${i}">${s.completed?'Mark Incomplete':'Mark Complete'}</button></div></div>`).join('');document.querySelectorAll('.toggle-active').forEach(b=>b.onclick=()=>toggleSection(Number(b.dataset.index),'active'));document.querySelectorAll('.toggle-complete').forEach(b=>b.onclick=()=>toggleSection(Number(b.dataset.index),'completed'));}
function toggleSection(index,key){const sections=Array.isArray(currentPlan.sections)?currentPlan.sections:[...STANDARD_SECTIONS];sections[index][key]=!sections[index][key];if(key==='completed'&&sections[index][key])sections[index].active=false;if(key==='active'&&sections[index][key])sections[index].completed=false;currentPlan.sections=sections;renderPlan();}
async function resetPlan(){const id=$('traineeSelect').value;if(!id){notice('Select a volunteer first.','error');return;}selected=volunteers.find(v=>v.id===id);currentPlan={uid:id,email:selected.email||'',name:selected.name||selected.email||'',assignedTrainerUid:auth.currentUser.uid,assignedTrainerEmail:auth.currentUser.email,status:'Assigned',sections:STANDARD_SECTIONS.map(x=>({...x})),notes:'',updatedAt:serverTimestamp()};renderPlan();await savePlan();}
async function savePlan(){try{if(!currentAccess?.trainer){notice('Trainer access required.','error');return;}if(!selected||!currentPlan){notice('Open a training plan first.','error');return;}if(!currentAccess?.admin&&$('assignedTrainerSelect').value!==auth.currentUser.uid){notice('You can only save plans assigned to yourself.','error');return;}const trainer=trainers.find(t=>t.id===$('assignedTrainerSelect').value)||{};const sections=Array.isArray(currentPlan.sections)?currentPlan.sections:STANDARD_SECTIONS;const required=sections.filter(s=>s.active||s.completed);const completedRequired=required.filter(s=>s.completed);const allRequiredComplete=required.length>0&&required.every(s=>s.completed);const payload={uid:selected.id,email:selected.email||'',name:selected.name||selected.email||'',assignedTrainerUid:$('assignedTrainerSelect').value,assignedTrainerEmail:trainer.email||auth.currentUser.email,assignedTrainerName:trainer.name||trainer.email||auth.currentUser.email,status:$('trainingStatusSelect').value,sections,notes:$('trainerNotes').value.trim(),requiredCount:required.length,completedCount:completedRequired.length,allRequiredComplete,updatedAt:serverTimestamp()};await setDoc(doc(db,'volunteer_training_plans',selected.id),payload,{merge:true});if(allRequiredComplete||payload.status==='Completed'){await updateDoc(doc(db,'volunteers',selected.id),{trainingCompleted:true,trainingCompletedAt:serverTimestamp(),trainerUid:payload.assignedTrainerUid,trainerEmail:payload.assignedTrainerEmail,updatedAt:serverTimestamp()});}else{await updateDoc(doc(db,'volunteers',selected.id),{trainingCompleted:false,trainerUid:payload.assignedTrainerUid,trainerEmail:payload.assignedTrainerEmail,updatedAt:serverTimestamp()});}notice('Training plan saved.','success');await loadData();}catch(e){console.error(e);notice('Training plan could not be saved. Check Firestore rules.','error');}}
function injectLogin(){document.body.insertAdjacentHTML('beforeend',`<div id="trainerGate" class="admin-gate"><form id="trainerLogin" class="card"><p class="eyebrow">Verified Trainer Login</p><h2>Training Management</h2><label>Email<input id="trainerEmail" type="email" required></label><label>Password<input id="trainerPassword" type="password" required></label><button class="btn primary full">Sign In</button><p class="notice" id="trainerLoginNotice"></p></form></div>`);$('trainerLogin').addEventListener('submit',async e=>{e.preventDefault();try{$('trainerLoginNotice').textContent='Signing in...';await signInWithEmailAndPassword(auth,$('trainerEmail').value.trim(),$('trainerPassword').value);}catch(err){$('trainerLoginNotice').textContent='Login failed.';$('trainerLoginNotice').className='notice error';}});const logout=document.createElement('button');logout.className='btn';logout.textContent='Sign Out';logout.onclick=()=>signOut(auth);document.querySelector('.nav-links')?.appendChild(logout);}
function showLogin(){$('trainerGate').classList.add('show')}function hideLogin(){$('trainerGate').classList.remove('show')}function notice(text,type=''){$('trainerNotice').textContent=text;$('trainerNotice').className='notice '+type}function setText(id,t){const el=$(id);if(el)el.textContent=t}function esc(t=''){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}